go-vela/cli

action/log/get.go, action/log/get_test.go, action/log/validate_test.go, action/log/view.go, action/log/view_test.go
* Added `go-vela/cli/internal/output.Dump` as an output option
* Added `go-vela/cli/internal/output.Spew` as an output option
* Fixed some typos in the tests for this package
=> improve(log): add extra output methods

internal/client/client.go, internal/client/client_test.go, internal/client/doc.go, internal/client/key.go, internal/client/validate.go, internal/client/validate_test.go
* Added a new `go-vela/cli/internal/client` pkg
* Added constants for the flag keys (`addr` and `token`) we parse for the client
* Added a `Parse()` function to `go-vela/cli/internal/client`
* Added tests for the `Parse()` function
* Added a `validate()` function to `go-vela/cli/internal/client`
* Added tests for the `validate()` function
=> feat(internal): add client pkg

action/build/restart.go, action/build/table.go, action/build/view.go, action/deployment/add.go, action/deployment/table.go, action/deployment/view.go, action/hook/table.go, action/hook/view.go, action/log/get.go, action/log/view.go, action/repo/add.go, action/repo/chown.go, action/repo/remove.go, action/repo/repair.go, action/repo/table.go, action/repo/update.go, action/repo/view.go, action/secret/add.go, action/secret/remove.go, action/secret/table.go, action/secret/update.go, action/secret/view.go, action/service/table.go, action/service/view.go, action/step/table.go, action/step/view.go, internal/output/driver.go, internal/output/stdout.go, internal/output/stdout_test.go, internal/output/validate_test.go
* Refactored `go-vela/cli/internal/output.Default()` to `go-vela/cli/internal/output.Stdout()`
* Updated `go-vela/cli/internal/output.DriverDefault` to `go-vela/cli/internal/output.DriverStdout`
* Updated all functions in `go-vela/cli/action` to use `go-vela/cli/internal/output.Stdout()`
=> refactor: rename output.Default to output.Stdout

cmd/cmds.go, cmd/completion.go, cmd/completion/bash.go, cmd/completion/zsh.go, cmd/vela-cli/main.go
This resolves https://github.com/go-vela/community/issues/19
**source <(vela completion bash)**           _Make sure bash version is 4 or above_
or
**source <(vela completion zsh)**
This will enable auto completion for the current zsh/bash session. To enable it permanently, we would need to copy the script to /etc/bash-completion.d
zsh snapshots:
bash snapshots:
=> Enable auto completion for bash/zsh current session

action/build_get.go, action/build_restart.go, action/build_view.go, action/deployment_add.go, action/deployment_get.go, action/deployment_view.go, action/hook_get.go, action/hook_view.go, action/log_get.go, action/log_view.go, action/repo_add.go, action/repo_chown.go, action/repo_get.go, action/repo_remove.go, action/repo_repair.go, action/repo_update.go, action/repo_view.go, action/secret_add.go, action/secret_get.go, action/secret_remove.go, action/secret_update.go, action/secret_view.go, action/service_get.go, action/service_view.go, action/step_get.go, action/step_view.go
* Update all `go-vela/cli/action/*` command files to use `go-vela/cli/internal/client.Parse()` function
=> refactor: use client.Parse in commands

action/completion/bash.go, action/completion/completion.go, action/completion/doc.go, action/completion/generate.go, action/completion/generate_test.go, action/completion/validate.go, action/completion/validate_test.go, action/completion/zsh.go, action/completion_generate.go, action/completion_generate_test.go
* Added a new `go-vela/cli/action/completion` pkg
* Created a `BashAutoComplete` constant for the auto completion script
* Created a `ZshAutoComplete` constant for the auto completion script
* Added a `Generate()` function to `go-vela/cli/action/completion`
* Added tests for the `Generate()` function
* Added a `Validate()` function to `go-vela/cli/action/completion`
* Added tests for the `Validate()` function
* Added a `CompletionGenerate` command to `go-vela/cli/action`
* Added a `completionGenerate()` function called by `CompletionGenerate` command
* Added tests for the `completionGenerate()` function
=> feat: add completion action and commands

.github/workflows/build.yml, .github/workflows/prerelease.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/reviewdog.yml, .github/workflows/test.yml, .github/workflows/validate.yml, .golangci.yml, Makefile, codecov.yml
* Add `.PHONY` tags to Makefile
* Add new `make` targets for upgrading dependencies
* Skip the `patch` status from codecov.io
* Add more linters to `golangci-lint`
* Update linter settings for `golangci-lint`
* Skip execution of some `golangci-lint` linters on Go test files
* Upgrade `actions/checkout` workflow to `v2`
* Add `go fix` to `validate` Action workflow
=> ci: refactor Makefile. improve linter setup. upgrade deps.

action/config/validate.go, action/config/view.go, action/config_generate.go, action/config_generate_test.go, action/config_remove.go, action/config_remove_test.go, action/config_update.go, action/config_update_test.go, action/config_view.go, action/config_view_test.go
* skip the `os.Stat()` check for the config file if the action is `generate`
* output the config file as a string if the action is `view`
* switch from `file` flag to global `config` flag when loading the configuration
=> fix: using config file with CLI

cmd/vela-cli/add.go, cmd/vela-cli/chown.go, cmd/vela-cli/generate.go, cmd/vela-cli/get.go, cmd/vela-cli/main.go, cmd/vela-cli/remove.go, cmd/vela-cli/repair.go, cmd/vela-cli/restart.go, cmd/vela-cli/update.go, cmd/vela-cli/validate.go, cmd/vela-cli/view.go
* organized the `main.go` into segments with comments
* cleaned up the global flags set in `main.go`
* update the `main.go` to use the private (local) subcommands setup in the package
* removed unnecessary `validate` function
* enabled `ShortOptionHandling` for all CLI subcommands
FYI:
https://github.com/urfave/cli/blob/master/docs/v2/manual.md#combining-short-options
=> refactor: update main for refactored subcommands

action/config/empty.go, action/config/empty_test.go, action/config/load.go, action/config/load_test.go
Currently, when attempting to load the configuration file if it's empty (file exists but no content) or if the file has content but values in the file are empty, the CLI will throw panics when setting the values.
This PR adds a `Empty()` function to the `go-vela/cli/action/config.ConfigFile` type so we skip setting any values immediately if none are present 👍 
This will also verify there is content in the values being loaded from the config file before attempting to set them in the context 👍
=> fix: load empty config file or values to prevent panics

action/config/load.go, action/load.go, cmd/vela-cli/log.go, cmd/vela-cli/main.go
This PR removes some of the global flags that are unusable in the `github.com/urfave/cli/v2` library.
The reason these flags no longer work is because some of these global flags are redeclared in each subcommand which will overwrite any value specified at the global level.
Although we are removing the global flags, technically you can still provide values at a "global" level by using the environment variables or the configuration file 👍
=> fix: remove unusable global flags

action/secret/view.go
Updated the default output to include the yaml secret syntax and details about the secret being returned.
Example:
```yaml
secret:
- name: foo1
key: github/foo1
engine: native
type: org
details:
name: foo1
id: 1
org: ocotocat
repo: '*'
team: ""
name: foo1
value: '[secure]'
type: org
images: []
events:
- push
- pull_request
- tag
- deployment
allowcommand: true```
=> enhancement(secret): add pipeline information with view

action/config/load.go, action/config/load_test.go, cmd/vela-cli/load.go, cmd/vela-cli/main.go
Based off internal team feedback and discussions.
The tl;dr is the way were trying to load the flags in the config file often lead to:
```sh
FATA[0000] no such flag -<flag_name>
```
This PR will now add extra logic to accomplish a few different things:
1. Skip loading the configuration file if `config` is provided as an argument to the CLI
* i.e. `vela generate config`, `vela update config`, `vela view config` etc
2. Load values from the configuration file only if they're present in the existing context
As an example, you're allowed to configure an `org` and `repo` in the configuration file:
```yaml
api:
addr: https://vela-server.localhost.com
token: someSuperSecureToken
org: MyOrg
repo: MyRepo
```
The problem is that not all commands will require those flags or have them defined. This …
=> fix: loading config file for CLI commands

action/log/get.go, action/log/view.go, version/version.go
This PR will ensure that we see the log data in string format rather than a byte array 👍 
```sh
$ vela get logs --org JordanBrockopp --repo vela-play --build 161
&[{0xc000328220 0xc000328240 0xc000328250 ...}]
```
```sh
$ vela get logs --org JordanBrockopp --repo vela-play --build 161
> Inspecting runtime network...
$ docker network inspect JordanBrockopp_vela-play_161
{
...
```
=> fix: ensure log data is outputted in string format

action/build_view.go, action/deployment_view.go, action/hook_view.go, action/repo_view.go, action/secret_get.go, action/service_view.go, action/step_view.go
This PR will make `yaml` be the default output for the `view` subcommand on certain resources.
Currently, this impacts the following commands:
* `vela view build`
* `vela view deployment`
* `vela view hook`
* `vela view service`
* `vela view step`
The following commands will not be impacted:
* `vela view log`
* `vela view secret`
=> refactor: make yaml output default for some view subcommands

action/hook_view.go
This removes the `-h` alias for the `--hook` flag when running the `vela view hook` subcommand.
Currently if you attempt to run that command you're met with a panic and stack trace (provided below).
This is caused by the `--help` and `-h` flags automatically appended to every command/subcommand by the CLI library we're using.
```sh
$ vela view hook --help                                                                                                                                                                                                       07:43:54 AM with Z0027PD at C02ZW5Y3MD6R •100%
hook flag redefined: h
panic: hook flag redefined: h
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00012d320, 0x171c980, 0xc000229241, 0x1a11500, 0x1, 0x16685ca, 0x9) …
```
=> fix: remove -h alias due to conflict with help

action/completion_generate.go, action/config_remove.go, action/pipeline_generate.go, action/repo_add.go, action/repo_update.go, action/secret_add.go, action/secret_update.go
When `cli.BoolFlag` has the default value of `true` you are unable to override it, so the next best option is to switch to `cli.StringFlag` and still use the `c.Bool("commands")` to parse whether it is true or false.
A simple program to validate what I'm saying is true:
```golang
package main
import (
"fmt"
"log"
"os"
"github.com/urfave/cli/v2"
)
func main() {
app := &cli.App{
Flags: []cli.Flag{
&cli.BoolFlag{
EnvVars: []string{"VELA_COMMAND", "SECRET_COMMAND"},
Name:    "commands",
Aliases: []string{"c"},
Usage:   "enable a secret to be used for a step with commands",
Value:   true,
},
},
}
app.Action = run
err := app.Run(os.Args)
if err != nil {
log.Fatal(err)
}
}
func run(c *cli.Context) error {
fmt.Println("commands", c.Bool("commands"))
err := exec()
return err
}
func exec() error { …
```
=> fix(args): switch from BoolFlag to StringFlag to reduce confusion

action/repo_add.go, action/repo_update.go
See https://github.com/go-vela/cli/pull/162 for more information.
This PR updates the `active` flag to have a default value of `true` 👍 
This change is made for the following subcommands:
* `vela add repo`
* `vela update repo`
=> refactor: update default active flag to true

action/config/load.go
Currently, if you have an `org` or `repo` with `config` in the name, it'll lead to weird issues when running CLI commands.
Example:
```sh
$ vela view build --org sampleOrg --repo sampleRepo-configs --build 1
FATA[0000] no client address provided
```
Running the CLI with `trace` level logging provides some insight into the issue:
```sh
$ VELA_LOG_LEVEL=trace vela view build --org sampleOrg --repo sampleRepo-configs --build 1
DEBU[0000] validating config file configuration
DEBU[0000] executing load for config file configuration
DEBU[0000] config arg provided in [view build --org sampleOrg --repo sampleRepo-configs --build 1] - skipping load for config file $HOME/.vela/config.yml
DEBU[0000] validating config file configuration
DEBU[0000] executing load for config file configuration …
```
=> fix: check if arg equals config

action/action.go, action/pipeline_compile.go, action/pipeline_compile_test.go, action/pipeline_expand.go, action/pipeline_expand_test.go, action/pipeline_validate.go, action/pipeline_view.go, action/pipeline_view_test.go, cmd/vela-cli/compile.go, cmd/vela-cli/expand.go, cmd/vela-cli/main.go, cmd/vela-cli/view.go
Part of the [Cargill/Target Hackathon](https://gophers.slack.com/archives/CNRRKE8KY/p1602194963000100) for Vela
Related to https://github.com/go-vela/server/pull/203 and https://github.com/go-vela/cli/pull/172
Dependent on https://github.com/go-vela/sdk-go/pull/63/
Originally, I had this as one big PR:
https://github.com/go-vela/cli/pull/170 
But that is a lot of lines and files changed to review in a single PR so I've since broken it down.
This adds a collection of new `pipeline` commands:
```
$ vela compile pipeline
$ vela expand pipeline
$ vela view pipeline
```
The new commands will be added in a subsequent PR 👍
=> feat: add new compile/expand pipeline commands

action/action.go, action/pipeline_exec.go, cmd/vela-cli/compile.go, cmd/vela-cli/exec.go, cmd/vela-cli/expand.go, cmd/vela-cli/main.go, cmd/vela-cli/restart.go
Part of the effort for https://github.com/go-vela/community/issues/54
This adds a `vela exec pipeline` command that will functionally do nothing 👍 
I'm currently focused on adding the "shell" for the command and will add some of the core logic in a later PR.
Also, I'm currently seeing GitHub falsely report no status checks for this PR even though they ran successfully 👍 
Here is a link to the Actions that have ran on this branch:
https://github.com/go-vela/cli/actions?query=branch%3Afeature%2Fpipeline%2Fexec_shell
=> feat: add shell for exec pipeline command

action/pipeline/exec.go, action/pipeline_exec.go
Part of the effort for https://github.com/go-vela/community/issues/54
When running a pipeline locally, we allow you to mount in the current working directory to the build.
However, we weren't explicitly providing permissions so the code is setup to default to read-only (`ro`).
This adds `:rw` to the end of the volume mount path to ensure we mount the volume with read-write permissions.
I also updated the examples for `vela exec pipeline` to show mounting local volumes with different permissions.
=> fix(pipeline): mount local volume in read-write mode

action/secret_update.go
closes https://github.com/go-vela/community/issues/178
=> fix(secrets): remove default events from update action

action/pipeline/exec.go, go.mod, go.sum
Part of the effort for https://github.com/go-vela/community/issues/54
Based off of https://github.com/go-vela/pkg-executor/pull/110
This will set the version information for the executor which is used in environment variables.
=> feat: add version information to executor

action/login.go
change will remove obsolete token upon login. the existing prompt that warns about overwrite of config already warns about config getting overwritten and the user has to opt-in to accept the action.
=> enhance(login): remove old token after login

action/deployment_add.go
Include example that clarifies the syntax required to utilize deployments for a specific tag.
=> docs(deployment): show example ref for tags

action/pipeline/exec.go, action/pipeline/pipeline.go, action/pipeline/validate.go, action/pipeline_exec.go, action/pipeline_validate.go, action/pipeline_validate_test.go, go.mod, go.sum
Allowing setting the pipeline type within the `exec` and `validate` functions.
xref: https://github.com/go-vela/community/issues/326
=> feat(pipeline): allow setting type

Makefile, version/version.go
This first part is updating the version output to provide a log message when the fallback value is used for the semantic tag.
This message should be displayed if the tag info isn't captured properly:
https://github.com/go-vela/cli/blob/0222b053482f3212684e7e6e1f45a1c1a41740d9/Makefile#L15-L19
The second part is using Go's `runtime.Version()` function to capture the version of `go` the app is built with:
https://pkg.go.dev/runtime#Version
Since we're relying on that function from the `runtime` library, we no longer need to capture that info in the `Makefile`.
Previously, we used to run the `go version` command and parse the value from the output:
https://github.com/go-vela/cli/blob/0222b053482f3212684e7e6e1f45a1c1a41740d9/Makefile#L21-L25
=> enhance: setting version information

command/repo/sync.go
When writing the docs for sync, I noticed that these environment variables are not consistent with what repo and orgs are called in the rest of the repo package. Small fix.
=> fix(repo): change sync flags to be consistent with repo package

.github/workflows/build.yml, .github/workflows/prerelease.yml, .github/workflows/publish.yml, .github/workflows/release.yml, .github/workflows/reviewdog.yml, .github/workflows/test.yml, .github/workflows/validate.yml, go.mod
Updates Go to 1.17, GitHub Actions pipelines included.
xref: go-vela/types#221
=> chore(deps): update go to 1.17

action/pipeline/validate.go
fixes the scenario where the default pipeline is named `.vela.yaml` instead of `.vela.yml`. So, if you haven't specified the filename explicitly it will error instead `... .vela.yml: no such file or directory`. It's picking `.vela.yml` because a file wasn't specified. Since we support both `.yml` and `.yaml` by default it probably shouldn't error. The `validateFile` function already accounts for both valid defaults.
=> fix(validate): handle .yaml default file

command/hook/view.go
`h` is a reserved alias for `--help`
leaving this in causes a panic:
```
$ vela view hook --org $VELA_ORG --repo $VELA_REPO --hook $VELA_HOOK
hook flag redefined: h
panic: hook flag redefined: h
```
=> fix(hook): remove 'h' from alias

action/pipeline/exec.go
fixes https://github.com/go-vela/community/issues/655
this essentially mimics https://github.com/go-vela/worker/blob/v0.14.0/cmd/vela-worker/exec.go#L135-L143. we don't have a timeout for local execution, so i didn't introduce another context or timeout.
=> fix(exec): make sure to call StreamBuild

command/repo/add.go
default events are dictated by server - don't set defaults events in the CLI when enabling a repository to play nicely with https://github.com/go-vela/server/pull/758
=> fix(events): use default events set on server

action/worker/add.go
return actual error message from API to help with troubleshooting
=> fix(register): show error message

.github/workflows/build.yml
should add a little speed boost for running the `build` workflow. it will parallelize building for each platform when possible - could even add arch into the mix.
ref: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
opportunity to do the same for release builds (on release/tag events). `make build` is baked into the `release.sh` script, so might need a bit of rework.
UPDATE:
comparing the build in this PR with the matrix addition versus another, it looks like we're shaving off almost 10 minutes of build time.
=> chore(ci/build): use matrix for builds

action/schedule/update.go, action/schedule/validate.go, command/schedule/update.go
fixes the following issues when updating schedules:
* unable to update "active" field without supplying "entry"
* schedule name was mistakenly passed in as repo name
* "add" action name was used for update action
=> fix(schedule): fix update action

action/secret/validate.go, action/secret/validate_test.go
Preparing patch release for v0.20.2 with these changes: https://github.com/go-vela/cli/pull/475
=> patch(v0.20.2/secrets): support schedule event for secrets

action/deployment/validate.go, action/deployment/validate_test.go, command/deployment/add.go
Closes https://github.com/go-vela/community/issues/423
Made possible by https://github.com/go-vela/server/pull/961
Also removing the default value of `production` as a deployment target. This seems like it could exacerbate a simple mistake if folks forget to provide a target when intending to target a non-prod environment.
Marking this breaking, as potential scripts that depended on those default values (mostly the target, as the ref will be populated with the default branch anyway) will now not work as they used to.
=> enhance(deploy)!: remove default value for ref in add deployment command

action/pipeline/exec.go, action/pipeline/pipeline.go, command/pipeline/exec.go
`vela exec pipeline` on a step with a `path` rule will never run that step
=> enhance(pipeline/exec): include changeset for ruleset matching

action/pipeline/exec.go, action/pipeline/pipeline.go, command/pipeline/exec.go
Figured it may be helpful for users who need certain images ran in privileged mode during a Vela build.
=> enhance(pipeline/exec): incorporate privileged image handling in runtime config

command/pipeline/exec.go, command/pipeline/validate.go, command/pipeline/validate_test.go
More parity with our actual compiler
=> fix(pipeline): include starlark exec limit to compiler flags in exec + validate

command/pipeline/exec.go
Due to [this line](https://github.com/go-vela/types/blob/1eae2f5e371bed7918c5d66e9507798f36ce4953/library/build.go#L194), all tags need to have a `refs/tags/` prefix in order to be properly compiled. 
Rather than rewrite some hot path code, I think just inserting the prefix if it's not there is fine enough with a log statement.
=> fix(exec): set tag prefix if user does not provide one

command/version/version.go
This flag is not supported in the `version` command (though it would be nice to supply a Vela server and retrieve the version of the server).
=> chore(version): Remove invalid flag from help text

action/pipeline/validate.go, action/pipeline/validate_test.go
Due to how the environment is set up, the exec pipeline command needs to have a tag value on a tag event.
```sh
$ vela exec pipeline --pipeline-type go --event tag
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/go-vela/types/library.(*Build).Environment(0xc0006d7560, {0x2cc080e, 0x9}, {0x2cb70f5, 0x4})
/Users/Z004X4Y/go/pkg/mod/github.com/go-vela/types@v0.23.0-rc2/library/build.go:198 +0x31dd
github.com/go-vela/server/compiler/native.environment(0xc000606968?, 0x0, 0xc0002b81a0, 0x0)
/Users/Z004X4Y/go/pkg/mod/github.com/go-vela/server@v0.23.0-rc2/compiler/native/environment.go:326 +0xaec
github.com/go-vela/server/compiler/native.(*client).EnvironmentBuild(0xc0002204b0)
.....
```
Changed to:
```sh
$ vela exec pipeline --pipeline-type go --event …
```
=> fix(pipeline): validate presence of tag on tag events to avoid panic

command/build/approve.go
this resulted in an inaccessible link
=> fix(typo): Approve -> approve

command/pipeline/validate.go
We've got the necessary logic packed in to the compiler code [here](https://github.com/go-vela/server/blob/16ef8aca2af613a41e517d77c11e03b915836fda/compiler/native/expand.go#L209-L247) to have `ValidateLocal` always use a compiler engine with `local` set to `true`.
- If the template is of type `file` and the engine is `local`, then it will fetch from the filesystem. 
- If the template is of type `github` and the engine is `local`, it will fallthrough and attempt to fetch using user provided credentials
- If the template is being replaced using `--template-file` it will source those from the filesystem like usual.
Closes https://github.com/go-vela/community/issues/916
=> fix(pipeline): always set local to true for validate local

action/config/load.go, cmd/vela-cli/main.go, command/settings/view.go
fixing a couple things.
- config load bug
- help copy pasta
- view settings missing color
=> fix: syntax highlighting

go.mod, go.sum, internal/git.go
closes https://github.com/go-vela/cli/security/dependabot/22. repo for current package seems to be abandoned.
=> fix(deps): switch giturls lib

.golangci.yml
same fix as applied here https://github.com/go-vela/server/pull/1142
=> fix(lint): use proper formats field

action/login/success_page.go
looks like this got missed in the previous release :shame:
=> fix: update logo on success page

command/worker/update.go
Previously we were always setting `w.Active` to the result of the local `active` variable, which will be false if the user does not provide the active flag.
=> fix(worker): only set active when provided

action/pipeline/exec.go, action/pipeline/pipeline.go, command/pipeline/exec.go
Added flags for skipping steps:
https://github.com/go-vela/cli/blob/a51e7aa04061a5c6c811c0cb89ce4e6a16559947/command/pipeline/exec.go#L137-L144
Works for steps, stages, anchors, yaml templates, nested yaml templates.
- Stages: **any** steps with the provided name will be skipped, across all stages.
- Templates and nested templates: prepend the template name(s) to the step name
- Step names with spaces: wrap in quotes, including template name(s).
```
$ vela exec pipeline --sk echo_hi --sk child_echo_hi --sk 'child_some grandchild_echo_hi'
```
https://github.com/go-vela/cli/blob/a51e7aa04061a5c6c811c0cb89ce4e6a16559947/action/pipeline/exec.go#L118-L171
Also corrected punctuation for proper display in command help output:
https://github.com/go-vela/cli/blob/a51e7aa04061a5c6c811c0cb89ce4e6a165 …
=> feat(local exec): add ability to skip steps

.github/renovate.json, command/pipeline/exec.go, command/pipeline/validate.go
custom regex manager in renovate is supposed to update container images from `urfave` command defaults. however, git image is many versions behind. ran `renovate` locally via `LOG_LEVEL=debug npx renovate --platform=local --repository-cache=reset` to verify that it would intend to update these images with these new changes (had to temp remove the "extends" part for that to work).
also decided to include registry url for the image references.
> [!NOTE]
> git image is purposefully one patch version behind to verify the new config works. expect that renovate will want to update the git image on its next run.
=> fix(renovate): container images

.github/renovate.json, command/pipeline/exec.go, command/pipeline/validate.go
https://github.com/go-vela/cli/pull/606 failed (see https://github.com/go-vela/cli/issues/255). the problem seems to be that it picks up values that we don't care to update inside `Value: "<image>"`, which didn't surface in local testing (unless i missed it). in this approach we're just copying [what we do on the server](https://github.com/go-vela/server/blob/0e450d5055d6b4d03f82e5b2fef1afc116e61b94/.github/renovate.json#L14) which has been working; we just have to add a comment for renovate to identify the values we care about.
=> fix(renovate): use go-vela/server setup to manage image updates

action/config/generate.go, action/config/load.go, action/config/remove.go, action/config/update.go, action/pipeline/generate.go, action/secret/add.go, action/secret/update.go, action/secret/view.go, action/settings/update.go, go.mod, internal/output/yaml.go
drops direct dependencies of deprecated yaml packages. see https://github.com/go-vela/server/commit/91ba0d571a96b953009c70b466febf316167934d for similar change.
=> chore(deps): use go.yaml.in/yaml/v3
