go-vela/cli

cmd/secret/update.go, main.go
https://goreportcard.com/report/github.com/go-vela/cli
=> Refactor to improve Go Report Card

cmd/secret/add.go, cmd/secret/get.go, cmd/secret/remove.go, cmd/secret/update.go, cmd/secret/view.go
Fixes https://github.com/go-vela/cli/issues/48
=> improvement: set default repo for org actions

cmd/build/get.go, cmd/build/view.go, cmd/chown.go, cmd/log/view.go, cmd/login.go, cmd/repair.go, cmd/repo/add.go, cmd/repo/get.go, cmd/repo/remove.go, cmd/repo/update.go, cmd/repo/view.go, cmd/secret/update.go, cmd/service/get.go, cmd/service/view.go, cmd/step/get.go, cmd/step/view.go
=> docs: change carval to vela

cmd/secret/add.go
server/api will handle defaults (see https://github.com/go-vela/server/pull/136)
=> enhancement(secrets): remove client-side event defaults

cmd/get.go, cmd/hook/get.go, cmd/hook/get_test.go, cmd/hook/util.go, cmd/hook/view.go, cmd/hook/view_test.go, cmd/view.go
this fixes https://github.com/go-vela/community/issues/16
=> feat: add get/view hook

action/build_get.go, action/build_restart.go, action/build_view.go, action/deployment_add.go, action/deployment_get.go, action/deployment_view.go, action/repo_add.go, action/repo_chown.go, action/repo_get.go, action/repo_remove.go, action/repo_repair.go, action/repo_update.go, action/repo_view.go, action/service_get.go, action/service_view.go, action/step_get.go, action/step_view.go
A various amount of improvements exist in this PR like:
* Added flag aliases (short flag names)
* Added extra environment variables
* Cleaned up flag descriptions
* Cleaned up command examples
* Added links to public Vela CLI docs
=> refactor: improve cli usability

internal/output/default.go, internal/output/dump.go, internal/output/json.go, internal/output/rawjson.go, internal/output/spew.go, internal/output/validate.go, internal/output/validate_test.go, internal/output/yaml.go
* Added a `validate()` function to `go-vela/cli/internal/output` to reduce LOC
* Added tests for the `validate()` function
* Added `Debug` and `Trace` log statements using `github.com/sirupsen/logrus`
=> chore(output): add logging statements

action/pipeline/doc.go, action/pipeline/generate.go, action/pipeline/generate_test.go, action/pipeline/pipeline.go, action/pipeline/stage.go, action/pipeline/stage_test.go, action/pipeline/step.go, action/pipeline/step_test.go, action/pipeline/testdata/default.yml, action/pipeline/testdata/go.yml, action/pipeline/testdata/java.yml, action/pipeline/testdata/node.yml, action/pipeline/testdata/stages_default.yml, action/pipeline/testdata/stages_go.yml, action/pipeline/testdata/stages_java.yml, action/pipeline/testdata/stages_node.yml, action/pipeline/validate.go, action/pipeline/validate_test.go, go.mod, go.sum
* Added a new `go-vela/cli/action/pipeline` pkg
* Added a `Generate()` function to `go-vela/cli/action/pipeline`
* Added tests for the `Generate()` function
* Added a `Validate()` function to `go-vela/cli/action/pipeline`
* Added tests for the `Validate()` function
* Added a `ValidateFile()` function to `go-vela/cli/action/pipeline`
* Added tests for the `ValidateFile()` function
=> feat: add pipeline action

action/action.go, action/pipeline/testdata/generate.yml, action/pipeline_generate.go, action/pipeline_generate_test.go, action/pipeline_validate.go, action/pipeline_validate_test.go
* Added a `PipelineGenerate` command to `go-vela/cli/action`
* Added a `pipelineGenerate()` function called by `PipelineGenerate` command
* Added tests for the `pipelineGenerate()` function
* Added a `PipelineValidate` command to `go-vela/cli/action`
* Added a `pipelineValidate()` function called by `PipelineValidate` command
* Added tests for the `pipelineValidate()` function
=> feat: add pipeline commands

.github/workflows/prerelease.yml, .github/workflows/publish.yml
Related to https://github.com/go-vela/cli/pull/168
=> fix: add fetch depth for tag history

action/login/success_page.go
fixes an issue with rendering the success page copy on systems where light mode is preferred 😎
=> fix(auth): success page rendering

action/build/cancel.go
https://github.com/go-vela/server/pull/277
=> fix(cancel): pull in changes to response body

.gitignore, action/pipeline/validate.go, action/pipeline/validate_test.go
closes https://github.com/go-vela/community/issues/202
=> enhance(validate): return error if config file does not exist

action/secret/validate.go, action/secret_update.go
Updating the CLI to match the behavior of the UI.
=> fix(secret): value is optional when action is update

action/pipeline/exec.go
closes https://github.com/go-vela/community/issues/305
=> fix(exec): set default ref on pull_request event

go.mod, go.sum, test/helpers.go
related to: https://github.com/go-vela/server/pull/460
=> fix(deps): address vulnerable jwt-go library

Makefile, release.sh
closes https://github.com/go-vela/community/issues/175
=> enhance: add binary for darwin arm64

.github/workflows/build.yml, .github/workflows/prerelease.yml, .github/workflows/publish.yml, .github/workflows/reviewdog.yml, .github/workflows/test.yml, .github/workflows/validate.yml
same as https://github.com/go-vela/types/pull/270
=> fix(actions): make sure to use latest Go version

.github/workflows/publish.yml
missed this https://github.com/go-vela/cli/pull/419 in another workflow
=> fix(ci): apply fix to publish step

action/pipeline/exec.go
fixes https://github.com/go-vela/community/issues/712
as the issue points out, when you run a local pipeline exec, docker resources aren't cleaned up. subsequent runs cause issues. you'd either have to manually clean up the resources or run something like `docker system prune ...` for a scorched earth approach to get back into a state where you can attempt to rerun the command.
this change fixes the core issue so users can re-run after canceling local pipeline execs. it does not address some of the other nice-to-haves in mentioned in the issue. the value add is minimal, imo, in part because the steps that have ran until the point of cancellation are printed already.
=> enhance(pipeline/exec): cleanup canceled builds

action/pipeline/exec.go
ref https://git.target.com/vela/feature-requests/issues/244
=> fix(exec): support yaml & yml

action/secret/validate.go, action/secret/validate_test.go
Ref: https://github.com/go-vela/community/issues/851
=> fix(secrets): allow schedule events for secrets

action/repo/validate.go, action/repo/validate_test.go
Follow up from https://github.com/go-vela/server/pull/1062
=> enhance(repo): update validation to include first-time option

action/secret/add.go, action/secret/secret.go, action/secret/update.go, command/secret/add.go, command/secret/update.go
to augment: https://github.com/go-vela/server/pull/1302
=> feat(secret): add/update repo allowlist
